---
title: "Stochastic Harp Seal Assessment Model (SHAM)"
author: "M. Biuw, T. A Øigård, and S. Smouth"
date: "27/09/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Original state-space method

In the original state-space model developed in Øigård and Skaug (2014), fecundity was modelled as a stochastic-process. For an initial period $y\in[y_0,y_s]$ fecundity $F_y$ is assumed to be constant (due to lack of observations), $F_y = f_{init}$. Starting in year $y_s$ a 1st order auto-regressive (AR) process $x_y = a_1x_{y−1} + u_y$ is used as a
perturbation around $f_{init}$. Here, $a_1$ is the auto-regressive parameter and $u_y$ is a zero mean normally distributed “innovation term” with standard deviation $\sigma$. Since we require $0\leq F_y\leq 1$ we employ the logistic transformation
$$F_y=\frac{\exp (\xi +x_y)}{1+\exp (\xi + x_y)},$$
where $\xi = \log \{f_{init}/(1-f_{init})\}$.

## Extended state-space model to include prey availability

We extend the original state-space model to include availability of capelin and cod. Capelin and cod have proved to have a significant effect on the condition of the harp seals. Capelin has a positive relationship, the more capelin, the better the condition of the harp seals. Cod, however, has a negative relationship with condition of the harp seals as it preys on capelin and therefore acts as a competitor for harp seals. We propose to replace the AR(1) process in the original state-space model with the following mixed model $x_y = a_1x_{y−1} + a_2capelin + a_3cod + u_y$ as a
perturbation around $f_{init}$. Here, $a_1$ is the auto-regressive parameter, $a_2$ is the fixed effect of capelin, $a_3$ is the fixed effect of cod, and $u_y$ is a zero mean normally distributed “innovation term” with standard deviation $\sigma$.

Data on total biomass ($TB$) are taken from ICES stock assessments: *http://standardgraphs.ices.dk/stockList.aspx*. We use capelin total biomass in the Barents Sea/Norwegian Sea as an index of prey availability, and total biomass of East Arctic cod as an index of competition. While cod data go back to 1946, capelin data are (so far) only available from 1972 onwards. However, an estimate of capelin biomass, reconstructed based on stomach contents of cod (Marshall et al. 2000), is available for the period 1946-1972. These data (except the 1972 data), have also been included. In modelling the total biomass of capelin and cod has been normalized.

## Sophies proposal

For the fecundity of the seals, let's sort out some definitions. 

'pregnancy rate' means the proportion of seals found to be pregnant that year when they are lethally sampled, based usually on ovaries from moulting animals. Symbol $\phi$ (this is a proportion or probability so no units)

'natality' means the probability of producing a live pup. Symbol $\nu$ (this is a proportion or probability so no units) 

The number of females pregnant in year $t$ given there are $n_t$ females in the population could look like this


$$n_{pregnant,t,age}\sim Binomial(n_t,\phi_{t,age})$$
$$n_{pregnant,t}=\sum_{ages} {n_{pregnant,t,age}}$$
Where the pregnancy rate is a response to environmental variables which I represent as a vector of different ones $\vec{x}$ e.g. capelin, SST etc. Parameters in this function are in vector $\vec{\theta}$

$$\phi_{t,age} = f(\vec{\theta},\vec{x}) ogive(age)$$
A very common type of formulation is to make $f(\vec{\theta},\vec{x})$ into a logistic equation which might go like this

$$f(\vec{\theta},\vec{x})=\frac{exp(\beta_0+\beta_{capelin}CapelinBiomass+\beta_{cod}CodBiomass)}{1+exp(\beta_0+\beta_{capelin}CapelinBiomass+\beta_{cod}CodBiomass))}$$



Note that I've also included a multiplier on the logistic function $ogive(age)$ to take account that fecundity changes with age. 

This approach could be used to estimate $\vec{\theta}$ i.e. the $\beta$ values, based on observations of $\phi_t$ , capelin and cod. 

Then some of those females go on to actually pup. The proportion that do is $Q$ and we could allow this to vary by year as well, but let's not for now!

$$n_{pups}\sim Binomial(n_{pregnant,t},Q)$$

This can all be embedded in the seal population model which updates the female population at every time step

